using System.Net.NetworkInformation;
using System.Transactions;
Console.Write ("Enter round trip miles:");
int roundTrip=Convert.ToInt32(Console.ReadLine());
Console.Write ("Enter miles per gallon:");
int milesPerGallon = Convert.ToInt32(Console.ReadLine());
Console.Write ("Enter price per gallon:");
double pricePerGallon = Convert.ToDouble(Console.ReadLine());
double gallonsNeeded = roundTrip / milesPerGallon; 
double fuelCost = gallonsNeeded * pricePerGallon;
Console.WriteLine("Gallons needed" + gallonsNeeded.ToString("F2"));
Console.WriteLine("Fuel cost" + fuelCost.ToString("C"));
Console.WriteLine("How many people are going?");
int people = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("How many pizzas?");
int Pizzas = Convert. ToInt32(Console.ReadLine());
Console.WriteLine ("Price per pizza:");
int costPerPizza = Convert.ToInt32(Console.ReadLine());
const double pizza = (8);
Console.WriteLine ("Price Per Pizza:" + costPerPizza.ToString("C"));
Console.WriteLine("Hours worked this week?");
Console.WriteLine("Hourly rate:");
const double taxRate = (0.18);
