using System.Net.NetworkInformation;
using System.Transactions;
Console.Write ("Enter round trip miles:");
int roundTrip=Convert.ToInt32(Console.ReadLine());
Console.Write ("Enter miles per gallon:");
int milesPerGallon = Convert.ToInt32(Console.ReadLine());
Console.Write ("Enter price per gallon:");
double pricePerGallon = Convert.ToDouble(Console.ReadLine());
double gallonsNeeded = (double)roundTrip / milesPerGallon; 
double fuelCost = gallonsNeeded * pricePerGallon;
Console.WriteLine("Gallons needed" + gallonsNeeded.ToString("F2"));
Console.WriteLine("Fuel cost" + fuelCost.ToString("C"));
Console.WriteLine("How many people are going?");
int people = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("How many pizzas?");
int pizzas = Convert. ToInt32(Console.ReadLine());
Console.WriteLine ("Price per pizza:");
double costPerPizza = Convert.ToDouble(Console.ReadLine());
const int slices = (8);
int totalSlices = pizzas*slices;
double slicesPerPerson = (double)totalSlices/people;
double pizzaCost = pizzas*costPerPizza;
Console.WriteLine ("Total slices: " + totalSlices);
Console.WriteLine("Slices per person: " + slicesPerPerson);
Console.WriteLine("Pizza Cost: "+pizzaCost); 
Console.WriteLine("Hours worked this week?");
int Hours = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Hourly rate: ");
double hourlyRate = Convert.ToDouble(Console.ReadLine());
const double taxRate = (0.18);
Double grossPay = hourlyRate * Hours;
Console.WriteLine("Gross pay: " + grossPay);
Double taxes = (grossPay*taxRate);
Console.WriteLine("Tax withheld: " + taxes);
Double takeHome = (grossPay - taxes);
Console.WriteLine("Take home pay: "+takeHome); 
Console.WriteLine("Trip total: " + (fuelCost + pizzaCost));
Console.WriteLine("Cost per person: " + (fuelCost + pizzaCost) / people);
Console.WriteLine("Take home pay per hour: " +(takeHome/Hours));
Double costPerPerson = (fuelCost + pizzaCost) / people;
Console.WriteLine("Hours you must work: " + (costPerPerson / (takeHome/Hours)));

